version: 1
build:
  main: ./cmd/nebud
  binary: nebud
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 39000000000000unebula
  mnemonic: entry garbage bike poem grunt negative easily annual miss happy license
    blur false fringe program picture inner tape dismiss eagle include quality drill
    master
- name: bob
  coins:
  - 5500000000000unebula
- name: faucet
  coins:
  - 5500000000000unebula
faucet:
  name: faucet
  coins:
  - 5500000000000unebula
  coins_max:
  - 1000000000unebula
  host: 0.0.0.0:4500
  port: 4500
genesis:
  app_state:
    gravity:
      delegate_keys:
      - eth_address: 0x9fc56f2e851e1ab2b4c0fc4f6344800f29652ffe
        orchestrator: nebula1zypqa76je7pxsdwkfah6mu9a583sju6xjavygg
        validator: nebulavaloper1zypqa76je7pxsdwkfah6mu9a583sju6xjettez
    staking:
      params:
        bond_denom: unebula
  chain_id: nebula-local-testnet
validators:
- name: alice
  bonded: 33500000000000unebula
